# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM0
firmware_version: 2
frame_id: neato_laser
laser_timeout: 3.0  # Timeout for lidar shutdown (Seconds)
motor_startup_enable: false #Lidar state at node boot
