footprint: [[0.16,-0.24],[-0.4,-0.24],[-0.4,0.24],[0.14,0.24]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 3.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_mark laser_clear
    laser_mark: {sensor_frame: base_laser, data_type: LaserScan, clearing: false, marking: true, topic: scan, inf_is_valid: false, expected_update_rate: 0.4}
    laser_clear: {sensor_frame: base_laser, data_type: LaserScan, clearing: true, marking: false, topic: scan_filtered, inf_is_valid: true, expected_update_rate: 0.4}

inflation:
    inflation_radius: 0.7
    