obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.16, -0.30], [-0.43,-0.30], [-0.43,0.30], [0.14,0.30]]
#robot_radius: 0.24
inflation_radius: 0.7
cost_scaling_factor: 4.0
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}


#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
