controller_frequency: 5.0
recovery_behavior_enabled: false
clearing_rotation_enabled: false

DWAPlannerROS:

  max_vel_x: 0.8
  min_vel_x: 0.0
  max_vel_y: 0.0 # diff drive
  min_vel_y: 0.0 # diff drive

  max_trans_vel: 0.75 # Slightly less than actual
  min_trans_vel: 0.1 # Never make 0...
  trans_stopped_vel: 0.1
  
  max_rot_vel: 5.0 # Slightly less than actual
  min_rot_vel: 0.4
  rot_stopped_vel: 0.4

  acc_lim_theta: 2.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0 # Differential Drive

  #Goal Tolerance
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15

  #Forward Simulation
  sim_time: 1.0
  vx_samples: 8
  vy_samples: 1
  vtheta_samples: 20

  #Trajectory Scoring
  path_distance_bias: 64.0 #32.0
  goal_distance_bias: 24.0 #24.0
  occdist_scale: 0.5   #0.01
  forward_point_distance: 0.325 # 0.325
  stop_time_buffer: 0.2 #0.2
  scaling_speed: 0.25 #0.25
  max_scaling_factor: 0.2 #0.2

  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #0.05
  
  #Debug
  publish_traj_pc: true
  publish_cost_grid_pc: true

  holonomic_robot: false
#  meter_scoring: true

