local_costmap:
  global_frame: odom
  robot_base_frame: /base_link
  rolling_window: true
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  width: 4.0
  height: 4.0
  # origin_x: -0.115
  resolution: 0.05
  transform_tolerance: 5.0 # seconds
